Repository chpc-tech-eval/scc, pull requests merged in 2024-07, with the labels that each got.

#101 Tut2/visual clarity
  tutorial1/README.md
  tutorial1/resources/openstack_instance_flavor.png
  tutorial1/resources/openstack_source_image.png
  tutorial1/resources/openstack_troubleshooting_delete_instance.png
  tutorial1/resources/openstack_troubleshooting_delete_volume.png
  tutorial1/resources/openstack_troubleshooting_dissociate_float_ip.png
  tutorial2/README.md
  tutorial2/resources/openstack_verify_network.png
Labels: documentation

#103 Tut2/visual clarity
  tutorial1/README.md
  tutorial1/resources/openstack_troubleshooting_dissociate_float_ip.png
  tutorial2/README.md
  tutorial2/hn.nft
  tutorial2/resources/ssh_bruteforce_attacks.png
Labels: documentation

#104 Tut2/ntp nfs
  tutorial2/README.md
  tutorial2/resources/ansible_ping_feedback.png
Labels: documentation

#105 Tut2/passwordless
  tutorial1/resources/openstack_troubleshooting_delete_instance.png
  tutorial2/README.md
  tutorial2/resources/openstack_hostsfile.png
Labels: documentation

#115 Added JupyterLab sections to Tutorial 4.
  tutorial3/README.md
  tutorial4/README.md
Labels: documentation, admin

#120 CHPC 2024 Student Cluster Competition Selection Round.
  CHPC Student Cluster Competition - Parts List - 2024.xlsx
  CHPC_2024_SCC_Local_Selection_Round_Timetable.pdf
  CHPC_2024_SCC_Local_Selection_Round_Timetable.png
  README.md
Labels: documentation

#124 Tut0/release
  CHPC_Student_Cluster_Competition_Parts_List_2024.xlsx
  README.md
  tutorial1/README.md
Labels: admin

#125 Fixed day 1 bugs, security groups and flavor names.
  README.md
  tutorial1/README.md
  tutorial1/resources/openstack_security_groups.png
Labels: admin

#128 Tut0/release
  README.md
  resources/.~lock.CHPC_SCC_2024_Technical_Knowledge_Assessment.docx#
  resources/CHPC_2024_SCC_Local_Selection_Round_Timetable.png
  resources/CHPC_SCC_2024_Technical_Knowledge_Assessment.docx
  resources/CHPC_Student_Cluster_Competition_Parts_List_2024.xlsx
  tutorial1/CHPC_2024_SCC_Local_Selection_Round_Timetable.pdf
  tutorial1/README.md
  tutorial2/README.md
  tutorial2/hn.nft
  tutorial2/resources/:etc:hosts.png
  tutorial2/resources/Selection_175.png
  tutorial2/resources/ansible_create_user_run_result.png
  tutorial2/resources/ansible_individual_host_access.png
  tutorial2/resources/ansible_ping_feedback.png
  tutorial2/resources/ansible_ping_servers.png
  tutorial2/resources/ansible_run_command_on_hosts.png
  tutorial2/resources/ansible_team_lead_user_verification.png
  tutorial2/resources/apache_default_page.png
  tutorial2/resources/cdexample.png
  tutorial2/resources/compute_node_basic_networking_commands.png
  tutorial2/resources/cpexamble.png
  tutorial2/resources/etchost.png
  tutorial2/resources/firefox_proxy_option.png
  tutorial2/resources/freeipa.png
  tutorial2/resources/generate_key_and_ssh_into_compute_node.png
  tutorial2/resources/history_command.png
  tutorial2/resources/home_dir_mounted.png
  tutorial2/resources/hostnamechange.png
  tutorial2/resources/htopcommand.png
  tutorial2/resources/install_tmux.png
  tutorial2/resources/ipaforeth0interface.png
  tutorial2/resources/ls_uid_different.png
  tutorial2/resources/lsdirectory.png
  tutorial2/resources/mvcommandexample.png
  tutorial2/resources/nfs_cat_pub_key_authorized.png
  tutorial2/resources/nsible_ping_servers.png
  tutorial2/resources/ntp.png
  tutorial2/resources/ntp_clients.png
  tutorial2/resources/ntp_source_for_compute_node.png
  tutorial2/resources/openstack_hostsfile.png
  tutorial2/resources/openstack_verify_network.png
  tutorial2/resources/openstack_vnc_access.png
  tutorial2/resources/rerun_command_from_history.png
  tutorial2/resources/rmcommand.png
  tutorial2/resources/rmcommandexample.png
  tutorial2/resources/selectSetting.png
  tutorial2/resources/sock5proxysettings.png
  tutorial2/resources/ssh_bruteforce_attacks.png
  tutorial2/resources/ssh_compute_node_passwd.png
  tutorial2/resources/ssh_example.avif
  tutorial2/resources/ssh_into_compute_node.png
  tutorial2/resources/ssh_keygen_login_compute_node.png
  tutorial2/resources/sshkeygen.png
  tutorial2/resources/tmux_btop_htop.png
  tutorial2/resources/tmux_running_htop_btop.png
  tutorial2/resources/tmux_ssh_run_tops.png
  tutorial2/resources/tut2_fig_part1_ssh_tunnel.png
  tutorial2/resources/zerotier-networks-empty.png
  tutorial2/resources/zerotier_auth.png
  tutorial2/resources/zerotier_new_network.png
Labels: admin

#129 Stag
  README.md
  resources/.~lock.CHPC_SCC_2024_Technical_Knowledge_Assessment.docx#
  resources/CHPC_2024_SCC_Local_Selection_Round_Timetable.png
  resources/CHPC_SCC_2024_Technical_Knowledge_Assessment.docx
  resources/CHPC_Student_Cluster_Competition_Parts_List_2024.xlsx
  tutorial1/CHPC_2024_SCC_Local_Selection_Round_Timetable.pdf
  tutorial1/README.md
  tutorial2/README.md
  tutorial2/hn.nft
  tutorial2/resources/:etc:hosts.png
  tutorial2/resources/Selection_175.png
  tutorial2/resources/ansible_create_user_run_result.png
  tutorial2/resources/ansible_individual_host_access.png
  tutorial2/resources/ansible_ping_feedback.png
  tutorial2/resources/ansible_ping_servers.png
  tutorial2/resources/ansible_run_command_on_hosts.png
  tutorial2/resources/ansible_team_lead_user_verification.png
  tutorial2/resources/apache_default_page.png
  tutorial2/resources/cdexample.png
  tutorial2/resources/compute_node_basic_networking_commands.png
  tutorial2/resources/cpexamble.png
  tutorial2/resources/etchost.png
  tutorial2/resources/firefox_proxy_option.png
  tutorial2/resources/freeipa.png
  tutorial2/resources/generate_key_and_ssh_into_compute_node.png
  tutorial2/resources/history_command.png
  tutorial2/resources/home_dir_mounted.png
  tutorial2/resources/hostnamechange.png
  tutorial2/resources/htopcommand.png
  tutorial2/resources/install_tmux.png
  tutorial2/resources/ipaforeth0interface.png
  tutorial2/resources/ls_uid_different.png
  tutorial2/resources/lsdirectory.png
  tutorial2/resources/mvcommandexample.png
  tutorial2/resources/nfs_cat_pub_key_authorized.png
  tutorial2/resources/nsible_ping_servers.png
  tutorial2/resources/ntp.png
  tutorial2/resources/ntp_clients.png
  tutorial2/resources/ntp_source_for_compute_node.png
  tutorial2/resources/openstack_hostsfile.png
  tutorial2/resources/openstack_verify_network.png
  tutorial2/resources/openstack_vnc_access.png
  tutorial2/resources/rerun_command_from_history.png
  tutorial2/resources/rmcommand.png
  tutorial2/resources/rmcommandexample.png
  tutorial2/resources/selectSetting.png
  tutorial2/resources/sock5proxysettings.png
  tutorial2/resources/ssh_bruteforce_attacks.png
  tutorial2/resources/ssh_compute_node_passwd.png
  tutorial2/resources/ssh_example.avif
  tutorial2/resources/ssh_into_compute_node.png
  tutorial2/resources/ssh_keygen_login_compute_node.png
  tutorial2/resources/sshkeygen.png
  tutorial2/resources/tmux_btop_htop.png
  tutorial2/resources/tmux_running_htop_btop.png
  tutorial2/resources/tmux_ssh_run_tops.png
  tutorial2/resources/tut2_fig_part1_ssh_tunnel.png
  tutorial2/resources/zerotier-networks-empty.png
  tutorial2/resources/zerotier_auth.png
  tutorial2/resources/zerotier_new_network.png
Labels: admin

#133 Tut0/release
  README.md
  tutorial2/README.md
Labels: documentation, admin

#134 Stag
  README.md
  tutorial2/README.md
Labels: documentation, admin

#136 Stag
  README.md
  tutorial2/README.md
Labels: admin

#139 Tut0/release
  tutorial2/README.md
Labels: admin

#140 Stag
  tutorial2/README.md
Labels: admin

#143 Tut3/release
  README.md
  tutorial1/CHPC_2024_SCC_Local_Selection_Round_Timetable.pdf
  tutorial1/README.md
  tutorial2/README.md
  tutorial2/resources/hn.nft
  tutorial3/README.md
  tutorial3/resources/An-example-of-P-by-Q-partitioning-of-a-HPL-matrix-in-6-processes-2x3-decomposition.png
  tutorial3/resources/MultiThreaded_HPL.png
  tutorial3/resources/format.pl
  tutorial3/resources/lj.in
  tutorial3/resources/openstack_instance_snapshot.png
  tutorial3/resources/qv_experiment.py
Labels: admin

#144 Fixed HPL details.
  README.md
  tutorial3/README.md
Labels: admin

#147 Tut3/release
  README.md
  tutorial2/README.md
Labels: admin

#149 Stag
  README.md
  tutorial2/README.md
Labels: admin

#132 Tut4/checklist
  tutorial4/README.md
Labels: documentation

#154 Tut4/monitoring update
  tutorial4/README.md
Labels: admin

#157 Merge stag into dev
  CHPC_2024_SCC_Local_Selection_Round_Timetable.pdf
  README.md
  resources/.~lock.CHPC_SCC_2024_Technical_Knowledge_Assessment.docx#
  resources/CHPC_2024_SCC_Local_Selection_Round_Timetable.png
  resources/CHPC_SCC_2024_Technical_Knowledge_Assessment.docx
  resources/CHPC_Student_Cluster_Competition_Parts_List_2024.xlsx
  tutorial1/README.md
  tutorial1/resources/openstack_security_groups.png
  tutorial2/README.md
  tutorial2/resources/hn.nft
  tutorial2/resources/zerotier-networks-empty.png
  tutorial2/resources/zerotier_auth.png
  tutorial2/resources/zerotier_new_network.png
  tutorial3/README.md
  tutorial3/resources/An-example-of-P-by-Q-partitioning-of-a-HPL-matrix-in-6-processes-2x3-decomposition.png
  tutorial3/resources/MultiThreaded_HPL.png
  tutorial3/resources/format.pl
  tutorial3/resources/lj.in
  tutorial3/resources/openstack_instance_snapshot.png
  tutorial3/resources/qv_experiment.py
Labels: documentation, admin

#159 Tut4/release
  README.md
  tutorial3/README.md
  tutorial4/README.md
  tutorial4/resources/circleci_create_organization.png
  tutorial4/resources/circleci_create_project00.png
  tutorial4/resources/circleci_create_project01.png
  tutorial4/resources/circleci_create_project02.png
  tutorial4/resources/circleci_create_project03.png
  tutorial4/resources/circleci_environment_variables.png
  tutorial4/resources/circleci_successful_deploy.png
  tutorial4/resources/github_create_new_repo.png
  tutorial4/resources/github_manage_access.png
  tutorial4/resources/openstack_application_creds.png
  tutorial4/resources/terraform_apply.png
  tutorial4/resources/terraform_install.png
  tutorial4/resources/terraform_install_init.png
  tutorial4/resources/terraform_plan.png
  tutorial4/resources/terraform_statefile.png
Labels: admin
